/**
 * @octrashield/dex-sdk/core
 *
 * Core modules: HFHE encryption, OCS01 transactions, types, constants, errors.
 */

// Constants
export {
  MERSENNE_PRIME,
  MERSENNE_BITS,
  MAX_PLAINTEXT,
  DEFAULT_NOISE_BUDGET,
  NOISE_COSTS,
  MIN_NOISE_BUDGET,
  FEE_TIERS,
  FEE_DENOMINATOR,
  PROTOCOL_FEE_FRACTION,
  MIN_TICK,
  MAX_TICK,
  MIN_SQRT_RATIO,
  MAX_SQRT_RATIO,
  MAX_SWAP_HOPS,
  DEFAULT_SLIPPAGE_BPS,
  MAX_SLIPPAGE_BPS,
  DEFAULT_DEADLINE_SECONDS,
  AI_EMA_ALPHA_BPS,
  AI_MIN_FEE_MULTIPLIER_BPS,
  AI_MAX_FEE_MULTIPLIER_BPS,
  AI_MEV_THRESHOLD_BPS,
  AI_SANDWICH_WINDOW_BLOCKS,
  NETWORKS,
  DEFAULT_NETWORK,
  CIPHERTEXT_PREFIX,
  MAX_CIPHERTEXT_BYTES,
  OCS01_VIEW_PREFIX,
  OCS01_CALL_PREFIX,
} from './constants.js';
export type { FeeTierId, NetworkConfig } from './constants.js';

// Types
export type {
  Address,
  TxHash,
  CiphertextHex,
  PoolId,
  PositionId,
  EncryptedU64,
  DecryptedValue,
  HfheKeyPair,
  OCS01ViewCall,
  OCS01CallTransaction,
  OCS01Transaction,
  TransactionReceipt,
  ContractEvent,
  TokenInfo,
  TokenBalance,
  TokenAllowance,
  CreatePoolParams,
  PoolInfo,
  PoolState,
  LiquidityPosition,
  AddLiquidityParams,
  RemoveLiquidityParams,
  LiquidityResult,
  TickData,
  Observation,
  SwapHop,
  SwapRoute,
  ExactInputParams,
  ExactOutputParams,
  DarkPoolSwapParams,
  SwapResult,
  SwapQuote,
  DynamicFee,
  VolatilityData,
  MevAlert,
  MevAlertType,
  MevRecommendation,
  RebalanceSuggestion,
  OctraShieldConfig,
  WalletState,
  ConnectionStatus,
  Paginated,
  Result,
  Subscription,
  OctraShieldError as OctraShieldErrorType,
} from './types.js';

// HFHE Encryption
export {
  generateKeyPair,
  encrypt,
  encryptNumber,
  encryptZero,
  decrypt,
  decryptValue,
  decryptNumber,
  encryptBatch,
  decryptBatch,
  simulateAdd,
  simulateSub,
  simulateMul,
  hasNoiseBudget,
  estimateRemainingOps,
  reencrypt,
  isValidCiphertext,
  isValidPlaintext,
  fieldAdd,
  fieldSub,
  fieldMul,
  fieldPow,
  fieldInverse,
  bytesToHex,
} from './hfhe.js';

// OCS01 Transactions
export {
  TransactionBuilder,
  encodeViewCall,
  encodeCallTransaction,
  signPayload,
  verifySignature,
  derivePublicKey,
} from './ocs01.js';

// Errors
export {
  OctraShieldError,
  EncryptionError,
  DecryptionError,
  NoiseBudgetExhausted,
  InvalidPlaintext,
  InvalidCiphertext,
  TransactionError,
  SignatureError,
  NonceError,
  DeadlineExpired,
  PoolNotFound,
  PoolAlreadyExists,
  InsufficientLiquidity,
  InvalidTickRange,
  KInvariantViolation,
  SlippageExceeded,
  RouteNotFound,
  MaxHopsExceeded,
  InsufficientBalance,
  InsufficientAllowance,
  MevDetected,
  AICircleUnavailable,
  ConnectionError,
  WalletNotConnected,
  NetworkMismatch,
  RpcError,
  isOctraShieldError,
  wrapError,
} from './errors.js';
